"""Alembic script template for migrations."""

"""add_missing_email_verification_columns

Revision ID: 7052b044339c
Revises: b0ca8163bf25
Create Date: 2025-10-07 05:06:45.332679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7052b044339c'
down_revision = 'b0ca8163bf25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
