"""Alembic script template for migrations."""

"""Initial database schema 2

Revision ID: e7cf46abb299
Revises: 1cd42f1c7145
Create Date: 2025-10-02 12:54:31.795475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cf46abb299'
down_revision = '1cd42f1c7145'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
