name: Security Scan

on:
    pull_request:
        branches: [develop, main]
    push:
        branches: [develop, main]
    schedule:
        - cron: "0 2 * * 1" # Weekly on Monday at 2 AM

jobs:
    backend-security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  pip install bandit safety semgrep

            - name: Run Bandit security scan
              run: |
                  bandit -r app/ -f json -o bandit-report.json
                  bandit -r app/ -ll
              continue-on-error: true

            - name: Run Safety dependency scan
              run: |
                  safety check --json --output safety-report.json
                  safety check
              continue-on-error: true

            - name: Run Semgrep security scan
              run: |
                  semgrep --config=auto app/ --json --output=semgrep-report.json
                  semgrep --config=auto app/
              continue-on-error: true

            - name: Upload security reports
              uses: actions/upload-artifact@v4
              with:
                  name: backend-security-reports
                  path: |
                      bandit-report.json
                      safety-report.json
                      semgrep-report.json

    container-security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build backend image
              run: |
                  docker build -t qeem-backend:security-test .

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              continue-on-error: true
              with:
                  image-ref: "qeem-backend:security-test"
                  format: "sarif"
                  output: "backend-trivy-results.sarif"
                  severity: "HIGH,CRITICAL"
                  exit-code: "1"

            - name: Upload Trivy scan results
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: "backend-trivy-results.sarif"

    secrets-scan:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run TruffleHog secrets scan
              uses: trufflesecurity/trufflehog@v3.81.7
              with:
                  path: ./
                  base: ${{ github.event.pull_request.base.sha }}
                  head: ${{ github.event.pull_request.head.sha }}
                  extra_args: --debug --only-verified
              continue-on-error: true

    dependency-review:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Dependency Review
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: high
                  allow-licenses: MIT, Apache-2.0, BSD-3-Clause, ISC
